# Generated by Django 5.2.3 on 2025-07-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suretrust_course', models.CharField(choices=[('SURETRUST_101', 'SURETRUST 101'), ('SURETRUST_102', 'SURETRUST 102'), ('SURETRUST_103', 'SURETRUST 103')], max_length=13)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
