name: Format Code

on:
  pull_request:
    types: [opened, synchronize]

# Add explicit permissions
permissions:
  contents: write
  pull-requests: write

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install and run Prettier
        run: |
          npm install --global prettier
          prettier --write "**/*.{js,jsx,ts,tsx,json,css,md,html}"

 vipulattri/jsassignments
      - name: Commit changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "style: format code with prettier"
          git push 

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Format code with prettier" 
main
